services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5043:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=userprofiledb;Username=postgres;Password=pass
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - api

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: userprofiledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
